### ISSUE TITLE
Better Upgrade experience

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/atom_cql_support#14]
The plugin needs a "beforeShutdown" or "beforeUpgrade" hook to shut down all the processes running in the background. Specifically, the language server and any executing tests.

**Comment by JPercival** [comment]
As a workaround, until this is addressed, make sure the workspace in Atom is closed and especially that all .cql files are closed before upgrading.

**Comment by JPercival** [comment]
Addressed with hardening around install / uninstall in release 2.9.0, and upcoming release 2.9.1
