### ISSUE TITLE
Add support for setting options using the cql-options.json file

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/atom_cql_support#19]
The latest translator (1.4.9-SNAPSHOT) includes support for reading and writing a translator options file for use in setting translator options. Include support for this capability in the Atom plugin. The CqlTranslatorOptions class in the Cql2Elm translator provides the capability, and the sample-content-ig includes an example options file:

https://github.com/cqframework/sample-content-ig/blob/master/input/cql/cql-options.json

The relevant code in the IG Publisher is here:
https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java#L240

**Comment by JPercival** [comment]
So, the work here is to add a way to the cql-language-server to detect that file and set the options appropriately and to do the same for the cql-evaluator.

**Comment by JPercival** [comment]
Resolved in release 2.11.0
