### ISSUE TITLE
CQL code will not execute after Upgrade to 2.8.1

### ISSUE THREAD

**Issue by preston7063** [cqframework/atom_cql_support#24]
Hello all,
Upgraded language-CQL to 2.8.1 within ATOM.  Could not execute the CQL code from ATOM.  Tried to uninstall from within ATOM and could not.  Removed contents from users/me/.atom/packages/ to remove the CQL plugin.  Able to reinstall.  Still cannot see CQL execute.  However, I now see the following error:

"CQL language server stopped unexpectedly.

Error: Could not find or load main class org.opencds.cqf.cql.ls.Main Caused by: java.lang.ClassNotFoundException: org.opencds.cqf.cql.ls.Main"   

I have uninstalled and reinstalled Java.  Both times I had version 8 build 271.  Removed and reinstalled Atom, both times build 1.52,   I could really use help.

Thanks,

Doug

**Comment by JPercival** [comment]
Apologies for the delayed response. Was this ever resolved?

The atom plugin downloads the cql-language-server from Maven. Occasionally, there are connection issues and we see similar error messages.
