### ISSUE TITLE
Ubuntu 20.04 OpenJDK11 language-cql parser error

### ISSUE THREAD

**Issue by DrMuir** [cqframework/atom_cql_support#25]
Atom language-CQL Java Version parsing error
Ubuntu 20.04 includes OpenJDK11 but includes multiple versions:

$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

$ which java
/usr/bin/java

$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64

I uninstalled packages and Atom and have successfully reinstalled both via Ubuntu software and via Atom.io
Latest versions of packages installed successfully for atom-ide-iu, ide-java and language-cql
Pop up error as follows:

language-cql requires Java 11 but could not determine your Java version.

Could not parse the Java '--showVersion' output
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

I suspect that the multiple line response is the issue for the language-cql parser.
(since Ubuntu 20.04 includes multiple versions of Java)
I suspect this may impact others running Linux/Ubuntu 20.04 (MacOs runs ok)

Appreciate your input, Thanks

**Comment by JPercival** [comment]
The issue is that the version detection logic doesn't handle a 4 part version number (11.0.9.1). Should be an easy fix.

**Comment by DrMuir** [comment]
Thank you!
-- 
*Peter Muir MD*
*E-mail:* peter.muir@esacinc.com
