### ISSUE TITLE
Breaking change for FHIR.id Types between CQL 1.4 and 1.5

### ISSUE THREAD

**Issue by IrickNcqa** [cqframework/atom_cql_support#34]
In CQL 1.4 (using extension v2.5.1), Patient.id (and FHIR id's in general) are interpreted as System.Strings.  When correctly typing, an error occurs:

CQL 1.4 extension v2.5.1
![image](https://user-images.githubusercontent.com/23317645/119047737-4c347b80-b98c-11eb-8396-dbd7e1beceb3.png)

CQL 1.4 exception on FHIR.id
![image](https://user-images.githubusercontent.com/23317645/119047774-5787a700-b98c-11eb-8ec5-d86eded041e3.png)

Then when switching to CQL 1.5 extension v2.9.1
![image](https://user-images.githubusercontent.com/23317645/119047825-65d5c300-b98c-11eb-9a3d-857e0202f3fc.png)

The typing is corrected to FHIR.id, but that is a breaking change from the CQL 1.4 behavior
![image](https://user-images.githubusercontent.com/23317645/119047872-78e89300-b98c-11eb-8c2c-561757317752.png)

**Comment by brynrhodes** [comment]
Thank you for submitting, this took a bit of digging, but the short story is that this is an issue in the 1.4.9-SNAPSHOT translator that was corrected in the 1.4.9 release of the translator:

1.4.9-SNAPSHOT had incorrect type String for id element of FHIR.Resource type:
https://github.com/cqframework/clinical_quality_language/blob/v1.4.9-SNAPSHOT/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-4.0.1.xml#L9643

1.4.9 Release corrected this to FHIR.id:
https://github.com/cqframework/clinical_quality_language/blob/v1.4.9/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-4.0.1.xml#L9520

The 2.5.1 release of the Atom plugin uses the 1.1.1-SNAPSHOT of the cql-language-server, which is using the 1.4.9-SNAPSHOT of the translator.
The first release of the cql-language-server that uses the 1.4.9 release of the translator is the 1.4.0-SNAPSHOT:
https://github.com/cqframework/atom_cql_support/blob/v2.7.0/package.json#L78

The 1.4.0-SNAPSHOT of the language server is used in the 2.7.0 release of the plugin, which is the last plugin before we introduced CQL 1.5 support:
https://github.com/cqframework/atom_cql_support/blob/v2.7.0/package.json#L78

So... if you use the 2.7.0 release of the Atom plugin, you'll get the correct behavior in CQL 1.4.

**Comment by JPercival** [comment]
Right now the plugins defaults to 1.5. If implement #19 this will be resolved. Requires some upstream work in the language server.

**Comment by JPercival** [comment]
#19 is implemented. You can pick the version of CQL desired wit the cql-options.json file.
